"""Domain package public surface."""

from __future__ import annotations

from mwa_ad_connector.domain.capabilities import (
    CATALOG,
    CapabilityMetadata,
    get_metadata,
    is_known_capability,
    is_mutation_capability,
)
from mwa_ad_connector.domain.enums import (
    ApprovalMode,
    ErrorCategory,
    HealthState,
    IdentifierType,
    MutationDisposition,
    ObjectType,
    OperationState,
    RiskLevel,
)
from mwa_ad_connector.domain.errors import (
    ERROR_METADATA,
    AmbiguousTargetError,
    ApprovalRequiredError,
    ConcurrentModificationError,
    DependencyUnavailableError,
    DomainError,
    ErrorCode,
    ErrorMetadata,
    IdempotencyCollisionError,
    PolicyDeniedError,
    ProtectedTargetError,
    RequestInvalidError,
    TargetNotFoundError,
    VerificationFailedError,
    http_status_for,
    is_retryable,
)
from mwa_ad_connector.domain.evidence import EntraEvidenceHint, VerificationEvidence
from mwa_ad_connector.domain.health import ComponentHealth, HealthStatus
from mwa_ad_connector.domain.identifiers import ObjectReference
from mwa_ad_connector.domain.objects import DirectoryGroup, DirectoryUser, OrganizationalUnit
from mwa_ad_connector.domain.operations import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    ApprovalContext,
    CallerContext,
    CapabilityRequest,
    MutationResult,
    OperationRecord,
    StateTransition,
    is_legal_transition,
    is_terminal,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CATALOG",
    "ERROR_METADATA",
    "TERMINAL_STATES",
    "AmbiguousTargetError",
    "ApprovalContext",
    "ApprovalMode",
    "ApprovalRequiredError",
    "CallerContext",
    "CapabilityMetadata",
    "CapabilityRequest",
    "ComponentHealth",
    "ConcurrentModificationError",
    "DependencyUnavailableError",
    "DirectoryGroup",
    "DirectoryUser",
    "DomainError",
    "EntraEvidenceHint",
    "ErrorCategory",
    "ErrorCode",
    "ErrorMetadata",
    "HealthState",
    "HealthStatus",
    "IdentifierType",
    "IdempotencyCollisionError",
    "MutationDisposition",
    "MutationResult",
    "ObjectReference",
    "ObjectType",
    "OperationRecord",
    "OperationState",
    "OrganizationalUnit",
    "PolicyDeniedError",
    "ProtectedTargetError",
    "RequestInvalidError",
    "RiskLevel",
    "StateTransition",
    "TargetNotFoundError",
    "VerificationEvidence",
    "VerificationFailedError",
    "get_metadata",
    "http_status_for",
    "is_known_capability",
    "is_legal_transition",
    "is_mutation_capability",
    "is_retryable",
    "is_terminal",
]
